---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: integration1
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
verifier:
  name: ansible
